name: Friday Daily on Discord

on:
  schedule:
    - cron: '0 10 * * 5' # Runs at 10:00 AM (UTC) every Friday
  workflow_dispatch: # Manually start up

jobs:
  compile-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install discord-webhook package
        run: pip install discord-webhook

      - name: Run Python Script and Send to Discord
        env:
          WEBHOOK_DISCORD: ${{ secrets.WEBHOOK_DISCORD }}
          BOT_TOKEN: ${{ secrets.BOT_DISCORD }}
        run: |
          python sender.py $WEBHOOK_DISCORD $BOT_DISCORD
